// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: duplicatepb/wrap.proto

package tpmwrappb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Secret_KeyType int32

const (
	Secret_ECC       Secret_KeyType = 0
	Secret_RSA       Secret_KeyType = 1
	Secret_HMAC      Secret_KeyType = 2
	Secret_AES       Secret_KeyType = 3
	Secret_KEYEDHASH Secret_KeyType = 4
)

// Enum value maps for Secret_KeyType.
var (
	Secret_KeyType_name = map[int32]string{
		0: "ECC",
		1: "RSA",
		2: "HMAC",
		3: "AES",
		4: "KEYEDHASH",
	}
	Secret_KeyType_value = map[string]int32{
		"ECC":       0,
		"RSA":       1,
		"HMAC":      2,
		"AES":       3,
		"KEYEDHASH": 4,
	}
)

func (x Secret_KeyType) Enum() *Secret_KeyType {
	p := new(Secret_KeyType)
	*p = x
	return p
}

func (x Secret_KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Secret_KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_duplicatepb_wrap_proto_enumTypes[0].Descriptor()
}

func (Secret_KeyType) Type() protoreflect.EnumType {
	return &file_duplicatepb_wrap_proto_enumTypes[0]
}

func (x Secret_KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Secret_KeyType.Descriptor instead.
func (Secret_KeyType) EnumDescriptor() ([]byte, []int) {
	return file_duplicatepb_wrap_proto_rawDescGZIP(), []int{0, 0}
}

type Secret_ParentKeyType int32

const (
	Secret_EndoresementECC Secret_ParentKeyType = 0
	Secret_EndorsementRSA  Secret_ParentKeyType = 1
	Secret_H2              Secret_ParentKeyType = 2
)

// Enum value maps for Secret_ParentKeyType.
var (
	Secret_ParentKeyType_name = map[int32]string{
		0: "EndoresementECC",
		1: "EndorsementRSA",
		2: "H2",
	}
	Secret_ParentKeyType_value = map[string]int32{
		"EndoresementECC": 0,
		"EndorsementRSA":  1,
		"H2":              2,
	}
)

func (x Secret_ParentKeyType) Enum() *Secret_ParentKeyType {
	p := new(Secret_ParentKeyType)
	*p = x
	return p
}

func (x Secret_ParentKeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Secret_ParentKeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_duplicatepb_wrap_proto_enumTypes[1].Descriptor()
}

func (Secret_ParentKeyType) Type() protoreflect.EnumType {
	return &file_duplicatepb_wrap_proto_enumTypes[1]
}

func (x Secret_ParentKeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Secret_ParentKeyType.Descriptor instead.
func (Secret_ParentKeyType) EnumDescriptor() ([]byte, []int) {
	return file_duplicatepb_wrap_proto_rawDescGZIP(), []int{0, 1}
}

type Secret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Type          Secret_KeyType       `protobuf:"varint,3,opt,name=type,proto3,enum=duplicatepb.Secret_KeyType" json:"type,omitempty"`
	ParentKeyType Secret_ParentKeyType `protobuf:"varint,4,opt,name=parentKeyType,proto3,enum=duplicatepb.Secret_ParentKeyType" json:"parentKeyType,omitempty"`
	Pcrs          []*PCRS              `protobuf:"bytes,5,rep,name=pcrs,proto3" json:"pcrs,omitempty"`
	Key           string               `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	ParentName    string               `protobuf:"bytes,7,opt,name=parentName,proto3" json:"parentName,omitempty"`
}

func (x *Secret) Reset() {
	*x = Secret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duplicatepb_wrap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_duplicatepb_wrap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_duplicatepb_wrap_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Secret) GetType() Secret_KeyType {
	if x != nil {
		return x.Type
	}
	return Secret_ECC
}

func (x *Secret) GetParentKeyType() Secret_ParentKeyType {
	if x != nil {
		return x.ParentKeyType
	}
	return Secret_EndoresementECC
}

func (x *Secret) GetPcrs() []*PCRS {
	if x != nil {
		return x.Pcrs
	}
	return nil
}

func (x *Secret) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Secret) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

type PCRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pcr   int32  `protobuf:"varint,1,opt,name=pcr,proto3" json:"pcr,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PCRS) Reset() {
	*x = PCRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duplicatepb_wrap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PCRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCRS) ProtoMessage() {}

func (x *PCRS) ProtoReflect() protoreflect.Message {
	mi := &file_duplicatepb_wrap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCRS.ProtoReflect.Descriptor instead.
func (*PCRS) Descriptor() ([]byte, []int) {
	return file_duplicatepb_wrap_proto_rawDescGZIP(), []int{1}
}

func (x *PCRS) GetPcr() int32 {
	if x != nil {
		return x.Pcr
	}
	return 0
}

func (x *PCRS) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_duplicatepb_wrap_proto protoreflect.FileDescriptor

var file_duplicatepb_wrap_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x70, 0x62, 0x2f, 0x77, 0x72,
	0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x75, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x70, 0x62, 0x22, 0x8a, 0x03, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2f,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x64,
	0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x2e, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x47, 0x0a, 0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x63, 0x72, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x70, 0x62, 0x2e, 0x50, 0x43, 0x52, 0x53, 0x52, 0x04, 0x70, 0x63, 0x72, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x3d, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03,
	0x45, 0x43, 0x43, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x53, 0x41, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x48, 0x4d, 0x41, 0x43, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x45, 0x53, 0x10,
	0x03, 0x12, 0x0d, 0x0a, 0x09, 0x4b, 0x45, 0x59, 0x45, 0x44, 0x48, 0x41, 0x53, 0x48, 0x10, 0x04,
	0x22, 0x40, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x45, 0x43, 0x43, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x53, 0x41, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x48, 0x32,
	0x10, 0x02, 0x22, 0x2e, 0x0a, 0x04, 0x50, 0x43, 0x52, 0x53, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x63,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x63, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x61, 0x6c, 0x72, 0x61, 0x73, 0x68, 0x69, 0x64, 0x31, 0x32, 0x33, 0x2f, 0x67, 0x6f,
	0x2d, 0x74, 0x70, 0x6d, 0x2d, 0x77, 0x72, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x70,
	0x6d, 0x77, 0x72, 0x61, 0x70, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_duplicatepb_wrap_proto_rawDescOnce sync.Once
	file_duplicatepb_wrap_proto_rawDescData = file_duplicatepb_wrap_proto_rawDesc
)

func file_duplicatepb_wrap_proto_rawDescGZIP() []byte {
	file_duplicatepb_wrap_proto_rawDescOnce.Do(func() {
		file_duplicatepb_wrap_proto_rawDescData = protoimpl.X.CompressGZIP(file_duplicatepb_wrap_proto_rawDescData)
	})
	return file_duplicatepb_wrap_proto_rawDescData
}

var file_duplicatepb_wrap_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_duplicatepb_wrap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_duplicatepb_wrap_proto_goTypes = []interface{}{
	(Secret_KeyType)(0),       // 0: duplicatepb.Secret.KeyType
	(Secret_ParentKeyType)(0), // 1: duplicatepb.Secret.ParentKeyType
	(*Secret)(nil),            // 2: duplicatepb.Secret
	(*PCRS)(nil),              // 3: duplicatepb.PCRS
}
var file_duplicatepb_wrap_proto_depIdxs = []int32{
	0, // 0: duplicatepb.Secret.type:type_name -> duplicatepb.Secret.KeyType
	1, // 1: duplicatepb.Secret.parentKeyType:type_name -> duplicatepb.Secret.ParentKeyType
	3, // 2: duplicatepb.Secret.pcrs:type_name -> duplicatepb.PCRS
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_duplicatepb_wrap_proto_init() }
func file_duplicatepb_wrap_proto_init() {
	if File_duplicatepb_wrap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_duplicatepb_wrap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_duplicatepb_wrap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PCRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_duplicatepb_wrap_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_duplicatepb_wrap_proto_goTypes,
		DependencyIndexes: file_duplicatepb_wrap_proto_depIdxs,
		EnumInfos:         file_duplicatepb_wrap_proto_enumTypes,
		MessageInfos:      file_duplicatepb_wrap_proto_msgTypes,
	}.Build()
	File_duplicatepb_wrap_proto = out.File
	file_duplicatepb_wrap_proto_rawDesc = nil
	file_duplicatepb_wrap_proto_goTypes = nil
	file_duplicatepb_wrap_proto_depIdxs = nil
}
